Add a mechanism for cleanly supporting interface files
Currently deploy.js and publish.js automatically try to deploy and
publish any .sol files they can find.  However interface files do not
need to be deployed, and attempting to do so results in this error:

    NomicLabsHardhatPluginError: You are trying to create a contract
    factory for the contract YourInterface, which is abstract and
    can't be deployed.

So add a mechanism for skipping deployment and publishing, and make it
easy to do this by adding interface files to hardhat.config.js.  Later
we may want to consider automatically detecting interface files, but
this is a simple solution for now.